name: Nix Build

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: nix develop -c cargo build --all-targets --release --workspace
